spring.application.name=customer-account-reconciliation
spring.datasource.url=jdbc:postgresql://localhost:5432/customer_account
spring.datasource.username=customer_account
spring.datasource.password=customer_account
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.liquibase.enabled=false
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=8081
logging.level.com.progressoft=INFO